-- CCE Production Database Dump
-- Generated by PHP Script

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
SET time_zone = "+00:00";

DROP TABLE IF EXISTS `companies`;
CREATE TABLE `companies` (
  `id` varchar(100) NOT NULL,
  `name` varchar(255) NOT NULL,
  `logo` varchar(255) DEFAULT NULL,
  `created_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  `description` text,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

INSERT INTO `companies` (`id`, `name`, `logo`, `created_at`, `description`) VALUES 
('cce-consult', 'CCE Consult', 'assets/image/companies-and-people/cce-logo.jpeg', '2026-05-25 21:30:27', NULL),
('courage-computers', 'Courage Computers', 'assets/image/companies-and-people/Courage-Computers-Logo.jpg', '2026-05-25 21:30:27', NULL),
('dnr-engineering', 'DnR Engineering & Construction', 'assets/image/companies-and-people/DnR.jpg', '2026-05-25 21:30:27', NULL),
('e7-technology', 'E7 Technology Solutions', 'assets/image/companies-and-people/E7_LOGO.png', '2026-05-25 21:30:27', NULL),
('enel-business-center', 'ENEL Business Center', 'assets/image/companies-and-people/enel.jpeg', '2026-05-25 21:30:27', NULL),
('lightroom-media', 'Lightroom Media Limited', 'assets/image/companies-and-people/lightroom-media-logo.png', '2026-05-25 21:30:27', NULL),
('school-farms', 'School Farms', 'assets/image/companies-and-people/school-farms.jpeg', '2026-05-25 21:30:27', NULL),
('spiritdriven-solutions', 'Spiritdriven Solutions', 'assets/image/companies-and-people/spiritdriven.png', '2026-05-25 21:30:27', NULL),
('surge-digital', 'Surge Digital', 'assets/image/companies-and-people/cce-logo.jpeg', '2026-05-25 21:30:27', NULL);

DROP TABLE IF EXISTS `events`;
CREATE TABLE `events` (
  `id` varchar(100) NOT NULL,
  `title` varchar(255) NOT NULL,
  `date_display` varchar(100) DEFAULT NULL,
  `start_date` date DEFAULT NULL,
  `end_date` date DEFAULT NULL,
  `start_datetime` datetime DEFAULT NULL,
  `end_datetime` datetime DEFAULT NULL,
  `timezone` varchar(50) DEFAULT 'Africa/Accra',
  `location` varchar(255) DEFAULT NULL,
  `faculty_id` varchar(10) DEFAULT NULL,
  `image` varchar(255) DEFAULT NULL,
  `excerpt` text,
  `registration_url` varchar(255) DEFAULT NULL,
  `is_featured` tinyint(1) DEFAULT '0',
  `created_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

INSERT INTO `events` (`id`, `title`, `date_display`, `start_date`, `end_date`, `start_datetime`, `end_datetime`, `timezone`, `location`, `faculty_id`, `image`, `excerpt`, `registration_url`, `is_featured`, `created_at`, `updated_at`) VALUES 
('annual-summit-2025', 'CCE Annual Summit', 'Nov 12–14', '2025-11-12', '2025-11-14', '2025-11-12 09:00:00', '2025-11-14 17:00:00', 'Africa/Accra', 'Accra, Ghana', NULL, 'assets/image/001.jpg', 'Our flagship convening—leaders across faculties gather for plenaries, workshops and practical labs that equip professionals to lead with excellence.', 'https://example.com/register/annual-summit-2025', '1', '2026-05-25 21:30:27', '2026-05-25 21:30:27'),
('excel-2024', 'EXCEL 2024 Conference', 'Nov 15–17, 2024', '2024-11-15', '2024-11-17', '2024-11-15 09:00:00', '2024-11-17 17:00:00', 'Africa/Accra', 'Accra, Ghana', NULL, 'assets/image/hero/001-w800.jpg', 'INSPIRED • INTENTIONAL • INTENSE - Our annual conference designed to inspire and equip young Christian professionals with foresight and insight. Three days of transformative learning, worship, and networking with 100+ Christian professionals.', '', '1', '2026-05-25 21:30:27', '2026-05-25 21:30:27'),
('regional-workshop-kumasi', 'Regional Practitioner Workshop', '2026-01-20', '2026-01-20', '2026-01-20', '2026-01-20 09:00:00', '2026-01-20 16:00:00', 'Africa/Accra', 'Kumasi', 'gad', 'assets/image/002.jpg', 'Hands-on workshops focused on pedagogy, governance toolkits and ethical decision-making for mid-career professionals.', 'https://example.com/register/regional-workshop-kumasi', '0', '2026-05-25 21:30:27', '2026-05-26 09:41:14'),
('regional-workshop-kumasi-2024', 'Regional Practitioner Workshop', '2024-01-20', '2024-01-20', '2024-01-20', '2024-01-20 09:00:00', '2024-01-20 16:00:00', 'Africa/Accra', 'Kumasi', NULL, 'assets/image/002.jpg', 'Hands-on workshops focused on pedagogy, governance toolkits and ethical decision-making for mid-career professionals.', 'https://example.com/register/regional-workshop-kumasi', '0', '2026-05-25 21:30:27', '2026-05-25 21:30:27'),
('research-symposium-2026', 'Research & Policy Symposium', '2026-03-09', '2026-03-09', '2026-03-09', '2026-03-09 09:00:00', '2026-03-09 17:00:00', 'Africa/Accra', 'Hybrid', 'gad', 'assets/image/003.jpg', 'Presentations from practitioners and academics on evidence-based interventions and policy recommendations for institutional reform.', 'https://example.com/register/research-symposium-2026', '0', '2026-05-25 21:30:27', '2026-05-26 09:40:37');

DROP TABLE IF EXISTS `hero_slides`;
CREATE TABLE `hero_slides` (
  `id` int NOT NULL AUTO_INCREMENT,
  `image_path` varchar(255) NOT NULL,
  `title` varchar(255) DEFAULT NULL,
  `description` text,
  `button_text` varchar(50) DEFAULT NULL,
  `button_link` varchar(255) DEFAULT NULL,
  `slide_order` int DEFAULT '0',
  `created_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=4 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

INSERT INTO `hero_slides` (`id`, `image_path`, `title`, `description`, `button_text`, `button_link`, `slide_order`, `created_at`) VALUES 
('1', 'assets/image/hero/001-w2000.jpg', 'Transforming Nations Through Christ', 'Equipping professionals to manifest high-end Seculo-Spiritual Aptitude across all spheres of influence.', 'Get Involved', 'get-involved.php', '1', '2026-05-25 22:04:59'),
('2', 'assets/image/hero/002-w2000.jpg', 'Governance & Development', 'Building functional systems and policies that drive real-life outcomes with eternal value.', 'View Faculties', 'faculty.php', '2', '2026-05-25 22:04:59'),
('3', 'assets/image/hero/003-w2000.jpg', 'Education & Training', 'Empowering the next generation of leaders with the manifold wisdom of God.', 'Read Our Charter', 'about.php', '3', '2026-05-25 22:04:59');

DROP TABLE IF EXISTS `news`;
CREATE TABLE `news` (
  `id` varchar(100) NOT NULL,
  `title` varchar(255) NOT NULL,
  `published_at` date DEFAULT NULL,
  `author` varchar(100) DEFAULT NULL,
  `excerpt` text,
  `featured_image` varchar(255) DEFAULT NULL,
  `faculty_id` varchar(10) DEFAULT NULL,
  `content` longtext,
  `created_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

INSERT INTO `news` (`id`, `title`, `published_at`, `author`, `excerpt`, `featured_image`, `faculty_id`, `content`, `created_at`, `updated_at`) VALUES 
('cce-launches-policy-brief', 'CCE publishes new policy brief on ethical governance', '2025-09-01', 'Dr. A. Example', 'A concise policy brief exploring ethics in public administration and practical reforms for institutional resilience.', 'assets/image/001.jpg', 'gad', '<p>The Cross-Cutting Excellence team today released a policy brief examining the ethical foundations of governance and recommending actionable reforms for institutions. The brief synthesizes best practices from practitioner-led research and field interventions, focusing on transparency, accountability, and capacity-building.</p><p>Key recommendations include stronger procurement oversight, professional development for middle managers, and measurement frameworks tied to ethical outcomes. Download the full brief from our resources page or contact the policy team for collaboration.</p>', '2026-05-25 21:30:27', '2026-05-26 10:04:48'),
('training-recap-july', 'Training recap: governance toolkit workshop', '2025-07-05', 'Faculty Team', 'A recap of our governance toolkit workshop with materials and recordings for participants.', 'assets/image/003.jpg', NULL, '<p>In July we ran a three-day governance toolkit workshop attended by 60 mid-career professionals. Sessions covered diagnostic assessments, stakeholder mapping, and ethics in procurement. Materials and session recordings are available for registered participants.</p><p>Contact the Faculty Team to request access to slides and datasets for your organisation.</p>', '2026-05-25 21:30:27', '2026-05-25 21:30:27'),
('volunteer-spotlight-sep', 'Volunteer spotlight: mentorship in action', '2025-08-18', 'CCE Communications', 'Highlighting the impact of volunteer mentors working with early-career professionals across our faculties.', 'assets/image/002.jpg', NULL, '<p>Our volunteers are the backbone of CCE’s mentorship programs. This month we visited mentorship cohorts in Accra and Kumasi to hear stories of transformation—professionals receiving coaching, applying governance toolkits, and launching community projects.</p><p>Read testimony from mentors and mentees and see recommended materials for facilitators.</p>', '2026-05-25 21:30:27', '2026-05-25 21:30:27');

DROP TABLE IF EXISTS `people`;
CREATE TABLE `people` (
  `id` varchar(100) NOT NULL,
  `name` varchar(255) NOT NULL,
  `role` varchar(255) DEFAULT NULL,
  `faculty_id` varchar(10) DEFAULT NULL,
  `company` varchar(255) DEFAULT NULL,
  `bio_short` text,
  `email` varchar(255) DEFAULT NULL,
  `linkedin` varchar(255) DEFAULT NULL,
  `photo` varchar(255) DEFAULT NULL,
  `image` varchar(255) DEFAULT NULL,
  `created_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

INSERT INTO `people` (`id`, `name`, `role`, `faculty_id`, `company`, `bio_short`, `email`, `linkedin`, `photo`, `image`, `created_at`) VALUES 
('alfred-adjabeng', 'Alfred Godwin Adjabeng', 'CCE Member', NULL, NULL, 'Development consultant, climate and carbon markets specialist, and social entrepreneur with over 10 years of experience.', '', '', 'assets/image/companies-and-people/alfred.jpeg', NULL, '2026-05-25 21:30:27'),
('anna-asem', 'Anna Asem', 'CCE Member', NULL, NULL, 'Member of the Cross-Cutting Excellence Network.', 'annaasem22@gmail.com', '', 'assets/image/companies-and-people/cce-logo.jpeg', NULL, '2026-05-25 21:30:27'),
('atiakpo-ransford', 'Atiakpo Ransford', 'CCE Member', NULL, NULL, 'Member of the Cross-Cutting Excellence Network.', 'ransford.atiakpo@gmail.com', '', 'assets/image/companies-and-people/ransford.jpg', NULL, '2026-05-25 21:30:27'),
('caleb-obipeh', 'Caleb Obipeh', 'CCE Member', NULL, NULL, 'Creative media professional and entrepreneur with a strong passion for visual storytelling, branding, and digital communication.', '', '', 'assets/image/companies-and-people/Caleb.jpeg', NULL, '2026-05-25 21:30:27'),
('cecil-ato-kwamena-dadzie', 'Cecil Ato Kwamena Dadzie', 'CCE Member', NULL, NULL, 'Communications, knowledge management and digital strategy professional dedicated to service, truth, and positive change.', 'cecildadzie@gmail.com', '', 'assets/image/companies-and-people/Cecil.jpeg', NULL, '2026-05-25 21:30:27'),
('cecil-dadzie', 'Cecil Dadzie', 'CCE Member', NULL, NULL, 'Member of the Cross-Cutting Excellence Network.', 'cecildadzie@gmail.com', '', 'assets/image/companies-and-people/cce-logo.jpeg', NULL, '2026-05-25 21:30:27'),
('courage-doe', 'Courage Doe', 'CCE Member', NULL, NULL, 'Member of the Cross-Cutting Excellence Network.', 'couragesotoranking@gmail.com', '', 'assets/image/companies-and-people/Courage-Doe.jpeg', NULL, '2026-05-25 21:30:27'),
('elias-adanu', 'Elias Adanu', 'CCE Member', NULL, NULL, 'Member of the Cross-Cutting Excellence Network.', 'eadanu@hotmail.com', '', 'assets/image/companies-and-people/cce-logo.jpeg', NULL, '2026-05-25 21:30:27'),
('emmanuel-mensah', 'Emmanuel Kwame Mensah', 'General Coordinator', 'gad', '', 'General Coordinator of Cross-Cutting Excellence (CCE) and international development consultant with over 20 years of UN experience.', 'kwamesdgs@gmail.com', '', 'assets/image/companies-and-people/Mr. Emmanuel Mensah.JPG', 'assets/image/companies-and-people/Mr. Emmanuel Mensah.JPG', '2026-05-25 21:30:27'),
('enoch-amoah', 'Enoch Amoah', 'CCE Member', NULL, NULL, 'Chartered Accountant and CEO of ENEL Business Centre with expertise in accounting and finance.', 'enochamoah81@gmail.com', '', 'assets/image/companies-and-people/enoch-amoah.jpeg', NULL, '2026-05-25 21:30:27'),
('eric-baidoo', 'Eric Baidoo', 'CCE Member', NULL, NULL, 'Member of the Cross-Cutting Excellence Network.', 'kbaidu7@gmail.com', '', 'assets/image/companies-and-people/Eric-Baidoo.png', NULL, '2026-05-25 21:30:27'),
('hana-brempong', 'Hana Brempong', 'CCE Member', NULL, NULL, 'Member of the Cross-Cutting Excellence Network.', 'hanabrempong@gmail.com', '', 'assets/image/companies-and-people/cce-logo.jpeg', NULL, '2026-05-25 21:30:27'),
('huda-sangari', 'Huda Sangari', 'CCE Member', NULL, NULL, 'Member of the Cross-Cutting Excellence Network.', 'nanasangari@gmail.com', '', 'assets/image/companies-and-people/cce-logo.jpeg', NULL, '2026-05-25 21:30:27'),
('jacqueline-antwi-danso', 'Jacqueline Antwi-Danso', 'CCE Member', NULL, NULL, 'Member of the Cross-Cutting Excellence Network.', 'j.antwidanso@gmail.com', '', 'assets/image/companies-and-people/cce-logo.jpeg', NULL, '2026-05-25 21:30:27'),
('kojo-botsio', 'Kojo Botsio', 'CCE Member', NULL, NULL, 'Member of the Cross-Cutting Excellence Network.', 'kojob511@gmail.com', '', 'assets/image/companies-and-people/cce-logo.jpeg', NULL, '2026-05-25 21:30:27'),
('lydia-boadi', 'Lydia Boadi', 'CCE Member', NULL, NULL, 'Member of the Cross-Cutting Excellence Network.', 'ohemaaboadi@gmail.com', '', 'assets/image/companies-and-people/cce-logo.jpeg', NULL, '2026-05-25 21:30:27'),
('miracle-hagan', 'Miracle K. Hagan', 'CCE Member', NULL, NULL, 'Member of the Cross-Cutting Excellence Network.', 'suave2g11@gmail.com', '', 'assets/image/companies-and-people/cce-logo.jpeg', NULL, '2026-05-25 21:30:27'),
('phoebe-mensah', 'Phoebe Mensah', 'CCE Member', NULL, NULL, 'Member of the Cross-Cutting Excellence Network.', 'phoebemensah15@gmail.com', '', 'assets/image/companies-and-people/cce-logo.jpeg', NULL, '2026-05-25 21:30:27'),
('rya-kuewor', 'Rya G. Kuewor', 'CCE Member', NULL, NULL, 'Expert at the World Economic Forum in International Development, Humanitarian Assistance, Migration, and SDG 8, with over 16 years of experience.', '', '', 'assets/image/companies-and-people/ria.jpeg', NULL, '2026-05-25 21:30:27'),
('seshie-michael', 'Seshie Michael', 'CCE Member', NULL, NULL, 'Member of the Cross-Cutting Excellence Network.', 'seshiemichael@hotmail.com', '', 'assets/image/companies-and-people/cce-logo.jpeg', NULL, '2026-05-25 21:30:27');

DROP TABLE IF EXISTS `site_settings`;
CREATE TABLE `site_settings` (
  `setting_key` varchar(100) NOT NULL,
  `setting_value` text,
  `updated_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`setting_key`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

INSERT INTO `site_settings` (`setting_key`, `setting_value`, `updated_at`) VALUES 
('contact_address', 'Accra, Ghana', '2026-05-25 22:04:59'),
('contact_email', 'info@ccegh.org', '2026-05-25 22:04:59'),
('contact_phone', '+233 123 456 789', '2026-05-25 22:04:59'),
('coordinator_image', 'assets/image/pics/coordinator.jpg', '2026-05-25 22:04:59'),
('coordinator_message', 'At CCE we train and equip God\'s Children in the areas of Governance and Development, Education and Training, Science and Technology, Philosophy and the Arts, Finance and Business, Relationships and Family, Missions and Apologetics, Communication and Media.<br><br>We are transforming our secular spaces and spheres of influence to the glory of our God, in Christ Jesus.<br><br>This anointing living in us makes us meek, hard working, patient, wise, bold, highly intelligent, efficient and driven by conviction. CCE provides what you need to make your life have eternal relevance: we focus on issues of eternal value. We are on the ground, engaged in local government and community development, national policy and programme implementation.<br><br>We train and equip volunteers and facilitators who drive change at national and internal levels, building bottom-up experience and top-down execution in a way that integrate functional systems into real life outcomes—with eternal value! We work in the arts and philosophy, guiding film-makers, theatre performers and creatives across the range to engineer the culture of godliness that provides oxygen for prosperity in communities, nations and generations.<br><br>CCE People are business owners and consultants spreading out across everywhere, reaching out to all the continents and creating the stable network yielding the critical mass of Christian Professionals required to transform our world until the kingdoms of this world become the kingdoms of our God and of his Christ.', '2026-05-25 22:04:59'),
('coordinator_name', 'The General Coordinator', '2026-05-25 22:04:59'),
('coordinator_quote', 'CCE is on the move—empowered by the anointing of the Holy Ghost to manifest high-end Seculo-Spiritual Aptitude (SSA).', '2026-05-25 22:04:59'),
('site_description', 'Cross-Cutting Excellence (CCE) mobilizes Christian professionals to reclaim and transform secular institutions through godly wisdom and professional excellence.', '2026-05-25 22:04:59'),
('site_title', 'CCE - Cross-Cutting Excellence', '2026-05-25 22:04:59'),
('social_facebook', 'https://facebook.com/cce', '2026-05-25 22:04:59'),
('social_instagram', 'https://instagram.com/cce', '2026-05-25 22:04:59'),
('social_linkedin', 'https://linkedin.com/company/cce', '2026-05-25 22:04:59'),
('social_twitter', 'https://twitter.com/cce', '2026-05-25 22:04:59'),
('welcome_message', 'Welcome to the CCE Official Website', '2026-05-25 22:04:59');

DROP TABLE IF EXISTS `users`;
CREATE TABLE `users` (
  `id` int NOT NULL AUTO_INCREMENT,
  `username` varchar(50) NOT NULL,
  `password_hash` varchar(255) NOT NULL,
  `role` varchar(20) DEFAULT 'admin',
  `created_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `username` (`username`)
) ENGINE=InnoDB AUTO_INCREMENT=10 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

INSERT INTO `users` (`id`, `username`, `password_hash`, `role`, `created_at`) VALUES 
('1', 'admin', '$2y$10$sWMqR1SHF0Acg6/j.fNDbe.LLm0z2FPCGccqqROBjAFSSgAuZfni2', 'admin', '2026-05-25 21:30:27');

